title: Slides Power Toys
description: Google Slides extension with useful features that complement native commands
baseurl: ""
url: "https://carlosmendonca.github.io/Slides-Power-Toys"
twitter_username: chemendonca
github_username:  CarlosMendonca

# Enable or disable the site search
search_enabled: false

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Slides Power Toys on GitHub":
    - "//github.com/carlosmendonca/slides-power-toys"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Carlos Mendonça. Distributed by an <a href=\"https://github.com/carlosmendonca/slides-power-toys/tree/master/LICENSE\">Apache 2.0 license.</a>"

color_scheme: spt

# Build settings
markdown: kramdown
permalink: pretty

remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"

plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
